// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFreeSpace(arg1) {
  return window['go']['main']['PickTargetService']['CheckFreeSpace'](arg1);
}

export function OpenFilePicker() {
  return window['go']['main']['PickTargetService']['OpenFilePicker']();
}

export function QuickFind() {
  return window['go']['main']['PickTargetService']['QuickFind']();
}

export function SaveSettings(arg1, arg2, arg3) {
  return window['go']['main']['PickTargetService']['SaveSettings'](arg1, arg2, arg3);
}
